/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_PlayListContainer */

#ifndef _Included_Spotify_PlayListContainer
#define _Included_Spotify_PlayListContainer
#ifdef __cplusplus
extern "C" {
#endif
#undef Spotify_PlayListContainer_PLAYLIST
#define Spotify_PlayListContainer_PLAYLIST 0L
#undef Spotify_PlayListContainer_PLAYLIST_FOLDER
#define Spotify_PlayListContainer_PLAYLIST_FOLDER 1L
#undef Spotify_PlayListContainer_PLAYLIST_CONTAINER
#define Spotify_PlayListContainer_PLAYLIST_CONTAINER 2L
#undef Spotify_PlayListContainer_TRACK
#define Spotify_PlayListContainer_TRACK 3L
#ifdef __cplusplus
}
#endif
#endif
