/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_PlayList */

#ifndef _Included_Spotify_PlayList
#define _Included_Spotify_PlayList
#ifdef __cplusplus
extern "C" {
#endif
#undef Spotify_PlayList_PLAYLIST
#define Spotify_PlayList_PLAYLIST 0L
#undef Spotify_PlayList_PLAYLIST_FOLDER
#define Spotify_PlayList_PLAYLIST_FOLDER 1L
#undef Spotify_PlayList_PLAYLIST_CONTAINER
#define Spotify_PlayList_PLAYLIST_CONTAINER 2L
#undef Spotify_PlayList_TRACK
#define Spotify_PlayList_TRACK 3L
#ifdef __cplusplus
}
#endif
#endif
