/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_Artist */

#ifndef _Included_Spotify_Artist
#define _Included_Spotify_Artist
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Spotify_Artist
 * Method:    GetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Spotify_Artist_GetName
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Artist
 * Method:    IsLoading
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Spotify_Artist_IsLoading
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Artist
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Spotify_Artist_Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
