/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_Image */

#ifndef _Included_Spotify_Image
#define _Included_Spotify_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Spotify_Image
 * Method:    GetData
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_Spotify_Image_GetData
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Image
 * Method:    IsLoading
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Spotify_Image_IsLoading
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Image
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Spotify_Image_Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
