/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_Session_AudioBufferStats */

#ifndef _Included_Spotify_Session_AudioBufferStats
#define _Included_Spotify_Session_AudioBufferStats
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
