/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_Track */

#ifndef _Included_Spotify_Track
#define _Included_Spotify_Track
#ifdef __cplusplus
extern "C" {
#endif
#undef Spotify_Track_PLAYLIST
#define Spotify_Track_PLAYLIST 0L
#undef Spotify_Track_PLAYLIST_FOLDER
#define Spotify_Track_PLAYLIST_FOLDER 1L
#undef Spotify_Track_PLAYLIST_CONTAINER
#define Spotify_Track_PLAYLIST_CONTAINER 2L
#undef Spotify_Track_TRACK
#define Spotify_Track_TRACK 3L

/*
 * Class:     Spotify_Track
 * Method:    Load
 * Signature: (ILjava/lang/String;)Z
 */
//JNIEXPORT jboolean JNICALL Java_com_Spotify_Track_Load
//  (JNIEnv *, jobject, jstring);

/*
 * Class:     Spotify_Track
 * Method:    GetDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_Spotify_Track_GetDuration
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Track
 * Method:    GetNumArtists
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_Spotify_Track_GetNumArtists
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Track
 * Method:    GetArtist
 * Signature: (I)LSpotify/Artist;
 */
JNIEXPORT jobject JNICALL Java_com_Spotify_Track_GetArtist
  (JNIEnv *, jobject, jint);

/*
 * Class:     Spotify_Track
 * Method:    GetAlbum
 * Signature: ()LSpotify/Album;
 */
JNIEXPORT jobject JNICALL Java_com_Spotify_Track_GetAlbum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
