/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_PlayListFolder */

#ifndef _Included_Spotify_PlayListFolder
#define _Included_Spotify_PlayListFolder
#ifdef __cplusplus
extern "C" {
#endif
#undef Spotify_PlayListFolder_PLAYLIST
#define Spotify_PlayListFolder_PLAYLIST 0L
#undef Spotify_PlayListFolder_PLAYLIST_FOLDER
#define Spotify_PlayListFolder_PLAYLIST_FOLDER 1L
#undef Spotify_PlayListFolder_PLAYLIST_CONTAINER
#define Spotify_PlayListFolder_PLAYLIST_CONTAINER 2L
#undef Spotify_PlayListFolder_TRACK
#define Spotify_PlayListFolder_TRACK 3L
#ifdef __cplusplus
}
#endif
#endif
