/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spotify_Album */

#ifndef _Included_Spotify_Album
#define _Included_Spotify_Album
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Spotify_Album
 * Method:    GetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Spotify_Album_GetName
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Album
 * Method:    IsLoading
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Spotify_Album_IsLoading
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Album
 * Method:    GetImage
 * Signature: ()LSpotify/Image;
 */
JNIEXPORT jobject JNICALL Java_Spotify_Album_GetImage
  (JNIEnv *, jobject);

/*
 * Class:     Spotify_Album
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Spotify_Album_Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
